language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt_packages:
      - nodejs

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - MOCK_SERVER_PORT=3000

before_install:
  - pushd $TRAVIS_BUILD_DIR/features/bootstrap/server
  - travis_retry npm install
  - nohup node server.js &
  - popd

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix --dry-run --verbose
  - vendor/bin/phpspec run -fprogress
  - vendor/bin/behat -fprogress
