language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=highest
  allow_failures:
    - php: hhvm

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - MOCK_SERVER_PORT=3000

before_install:
  - nohup composer run-script mock-server &

before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install --prefer-dist -n; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-dist -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update --prefer-dist -n; fi;

script:
  - composer run-script specs-ci
  - composer run-script examples-ci
  - composer run-script lint
