language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  global:
    - MOCK_SERVER_PORT=3000

before_install:
  - nohup composer run-script mock-server &

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - composer run-script specs-ci
  - composer run-script examples-ci
  - composer run-script lint

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
